version: '3'
services:
  weaviate:
    image: semitechnologies/weaviate:1.21.5
    container_name: weaviate
    env_file:
      - .env
    networks:
      - dev      
    volumes:
      - ./weaviate_data:/var/lib/weaviate/data

networks:
  dev:
    external: true